# Generated by Django 3.2.24 on 2024-03-14 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('saved_street_address1', models.CharField(blank=True, max_length=60, null=True)),
                ('saved_street_address2', models.CharField(blank=True, max_length=60, null=True)),
                ('saved_town_or_city', models.CharField(blank=True, max_length=60, null=True)),
                ('saved_county', models.CharField(blank=True, max_length=10, null=True)),
                ('saved_postcode', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
