# Generated by Django 3.2.24 on 2024-03-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20240227_0940'),
        ('profiles', '0002_auto_20240315_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_breads',
            field=models.ManyToManyField(blank=True, related_name='favorites', to='products.BreadProduct'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_pastries',
            field=models.ManyToManyField(blank=True, related_name='favorites', to='products.PastryProduct'),
        ),
    ]
