# Generated by Django 3.2.24 on 2024-03-15 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20240315_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_breads',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_pastries',
        ),
    ]
