# Generated by Django 3.2.24 on 2024-03-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=70, null=True)),
                ('email', models.EmailField(max_length=320)),
                ('message', models.TextField()),
            ],
        ),
    ]
