# Generated by Django 3.2.24 on 2024-03-31 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_newsletteremails'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('discount_value', models.IntegerField()),
                ('is_percentage', models.BooleanField()),
                ('min_spending', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='newsletteremails',
            options={'verbose_name_plural': 'Newsletter emails'},
        ),
        migrations.RemoveField(
            model_name='newsletteremails',
            name='received_codes',
        ),
        migrations.RemoveField(
            model_name='newsletteremails',
            name='used_codes',
        ),
        migrations.AddField(
            model_name='newsletteremails',
            name='received_codes',
            field=models.ManyToManyField(blank=True, null=True, related_name='pending_subscribers', to='contact.DiscountCode'),
        ),
        migrations.AddField(
            model_name='newsletteremails',
            name='used_codes',
            field=models.ManyToManyField(blank=True, null=True, related_name='subscribers_used', to='contact.DiscountCode'),
        ),
    ]
