# Generated by Django 3.2.24 on 2024-04-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20240331_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletteremails',
            name='used_codes',
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='min_spending',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='newsletteremails',
            name='received_codes',
            field=models.ManyToManyField(blank=True, related_name='pending_subscribers', to='contact.DiscountCode'),
        ),
    ]
