# Generated by Django 3.2.24 on 2024-04-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_auto_20240401_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletteremails',
            name='email',
            field=models.EmailField(max_length=320),
        ),
    ]
