# Generated by Django 3.2.24 on 2024-03-05 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=32)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('bake_date', models.DateTimeField()),
                ('delivery', models.BooleanField(default=False)),
                ('customer_note', models.TextField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=320)),
                ('phone_number', models.CharField(max_length=20)),
                ('street_address1', models.CharField(max_length=60)),
                ('street_address2', models.CharField(blank=True, max_length=60, null=True)),
                ('town_or_city', models.CharField(max_length=60)),
                ('county', models.CharField(max_length=10)),
                ('postcode', models.CharField(blank=True, max_length=10, null=True)),
                ('cart_total', models.IntegerField()),
                ('delivery_cost', models.IntegerField()),
                ('grand_total', models.IntegerField()),
                ('cart_items', models.TextField()),
                ('stripe_pid', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('lineitem_total', models.IntegerField()),
                ('prop_shape', models.CharField(blank=True, max_length=30, null=True)),
                ('prop_size', models.CharField(blank=True, max_length=30, null=True)),
                ('prop_contents', models.CharField(blank=True, max_length=30, null=True)),
                ('prop_type', models.CharField(blank=True, max_length=30, null=True)),
                ('prop_color', models.CharField(blank=True, max_length=10, null=True)),
                ('prop_icing', models.CharField(blank=True, max_length=30, null=True)),
                ('prop_decoration', models.CharField(blank=True, max_length=30, null=True)),
                ('prop_text', models.CharField(blank=True, max_length=40, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='checkout.order')),
            ],
        ),
    ]
