# Generated by Django 3.2.24 on 2024-03-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart_items',
        ),
        migrations.AlterField(
            model_name='order',
            name='bake_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
