# Generated by Django 3.2.24 on 2024-03-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20240307_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='grand_total',
            field=models.IntegerField(default=0),
        ),
    ]
