# Generated by Django 3.2.24 on 2024-03-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20240307_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bake_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
