# Generated by Django 3.2.24 on 2024-03-25 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_userprofile_user'),
        ('checkout', '0006_alter_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.userprofile'),
        ),
    ]
