# Generated by Django 3.2.24 on 2024-03-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_auto_20240222_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bread_prop_shapes', models.TextField(blank=True, null=True)),
                ('bread_prop_sizes', models.TextField(blank=True, null=True)),
                ('bread_prop_contents', models.TextField(blank=True, null=True)),
                ('pastry_prop_types', models.TextField(blank=True, null=True)),
                ('pastry_prop_contents', models.TextField(blank=True, null=True)),
                ('pastry_prop_colors', models.TextField(blank=True, null=True)),
                ('pastry_prop_icing', models.TextField(blank=True, null=True)),
                ('pastry_prop_decorations', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Site Data',
            },
        ),
    ]
