# Generated by Django 3.2.24 on 2024-02-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='pastryproduct',
            name='prop_text',
            field=models.BooleanField(default=False),
        ),
    ]
