# Generated by Django 3.2.24 on 2024-02-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20240222_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastryproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
