# Generated by Django 3.2.24 on 2024-02-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_pastryproduct_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastryproduct',
            name='image_url',
        ),
        migrations.AddField(
            model_name='pastryproduct',
            name='prop_color',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
