# Generated by Django 3.2.24 on 2024-02-27 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20240223_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pastryproduct',
            old_name='prop_toppings',
            new_name='prop_decoration',
        ),
        migrations.AlterField(
            model_name='pastryproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grouped_pastries', to='products.category'),
        ),
        migrations.AlterField(
            model_name='pastryproduct',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='BreadProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('batch_size', models.IntegerField()),
                ('ingredients', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('prop_shape', models.JSONField(blank=True, null=True)),
                ('prop_size', models.JSONField(blank=True, null=True)),
                ('prop_contents', models.JSONField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grouped_breads', to='products.category')),
            ],
        ),
    ]
