# Generated by Django 3.2.24 on 2024-03-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20240315_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breadproduct',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='pastryproduct',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
