# Generated by Django 3.2.24 on 2024-04-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20240320_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breadproduct',
            name='image',
            field=models.ImageField(upload_to='images/products/breads/'),
        ),
        migrations.AlterField(
            model_name='pastryproduct',
            name='image',
            field=models.ImageField(upload_to='images/products/pastries/'),
        ),
    ]
